### ISSUE TITLE
YouTube feed preview is sometimes broken

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#12]
Linux, Firefox 103.*, List Feeds 1.9.15

ex. https://www.youtube.com/user/Mozilla

sometimes the feed preview is just unformatted text such as...

```
yt:channel:UCajipi80aORRDz6gZ8ZyCWw UCajipi80aORRDz6gZ8ZyCWw Mozilla Mozilla https://www.youtube.com/channel/UCajipi80aORRDz6gZ8ZyCWw 2006-01-07T09:55:21+00:00 yt:video:aOPStUtmjCM aOPStUtmjCM UCajipi80aORRDz6gZ8ZyCWw Podcast: The Tech We Won’t Build Mozilla https://www.youtube.com/channel/UCajipi80aORRDz6gZ8ZyCWw 2022-08-18T18:00:00+00:00 2022-08-18T18:00:00+00:00 Podcast: The Tech We Won’t Build Where should tech builders draw the line on AI for military or surveillance? Just because it can be built, doesn’t mean it should be. At what point do we blow the whistle, call out the boss, and tell the world? In this episode o ...
```

**Comment by igorlogius** [comment]
That looks strange.  
Is it just one continuous line of text that is displayed? 
Can you maybe share a screenshot?

**Comment by atomGit** [comment]
it's all 1 line, but wrapped

i wasn't able to capture a log - every time i open the dev console on that youtube page the tab crashes

![feed](https://user-images.githubusercontent.com/1817307/189482758-a454ae31-a2b4-49fc-82c2-ca159c7c9132.png)

**Comment by igorlogius** [comment]
@atomGit 
I see that the preview is still loaded in in the popup, so i assume that you are still on the previous version. 
Try updating to the current one and check if the error persists.

**Comment by atomGit** [comment]
it's the same with the *.16 version - i just tested again in a fresh profile...

" This XML file does not appear to have any style information associated with it. The document tree is shown below. "

i don't think it's a YT issue though because [Feed Preview](https://addons.mozilla.org/en-US/firefox/addon/feed-preview/) works correctly

**Comment by igorlogius** [comment]
@atomGit 

Sorry, but firefox in a fresh profile and my addon in version  *.16 
both feeds on https://www.youtube.com/user/Mozilla 

- https://www.youtube.com/feeds/videos.xml?user=Mozilla
- https://www.youtube.com/feeds/videos.xml?channel_id=UCajipi80aORRDz6gZ8ZyCWw

Look like this for me: 

![snip_20220910-172759](https://user-images.githubusercontent.com/67047467/189490286-3d19d51c-ee74-44e2-8a64-145e30b589ba.png)

![snip_20220910-172840](https://user-images.githubusercontent.com/67047467/189490315-2500a01d-8dcc-4d1a-9781-0020798f3007.png)

So i have to assume that you either made some firefox settings changes.
To confirm this, you can try creating a 2nd (fresh) profile and only installing list-feeds and then check if the issue is still reproducable. 

Oh, and please comeback and tell me what  discovered. I am curious too. :) Might be something i'll have to add to the addon notes, so others dont have the same issue.

**Comment by atomGit** [comment]
strange indeed

my tests were conducted on a completely new profile, no changes whatsoever, and the only ext. was List Feeds

the only thing i can add is that List Feeds used to work on bitchute some time ago, so i don't know what changed

Manjaro ships with some default prefs in `/lib64/firefox/browser/defaults/preferences/vendor.js` but i'm sure they are irrelevant  

```js
// Use LANG environment variable to choose locale
pref("intl.locale.requested", "");

// Use system-provided dictionaries
pref("spellchecker.dictionary_path", "/usr/share/hunspell");

// Disable default browser checking.
pref("browser.shell.checkDefaultBrowser", false);

// Don't disable extensions in the application directory
pref("extensions.autoDisableScopes", 11);
```
