### ISSUE TITLE
why the 2 extensions on AMO - detect feeds & list feeds?

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#2]

**Comment by igorlogius** [comment]
Hello, 

thanks for taking interesst.

Essentially both addons have a slightly differnt usercase and  permission set. 

- `list-feeds`, does nothing until a user clicks on the toolbar button and only required the `activeTab` permission  to work. 
- `detect-feed`, automatically injects a content-script in each visited page to find feeds and show the pageAction icon, when at least one is found. This requires the addional host permission <all_urls> , which is a very broad permission.

Since the <all_urls> permission ... is a very powerful one and some people might feel uncomfortable giving it to a rather minor addon, like a feed detection i thought giving them the power to choose would be a good idea. 

Hope this explaination helps and that at least one of the addons fits your requirements. 
Havea nice day. Later, maybe.

**Comment by igorlogius** [comment]
To be fair,  i could maybe merge the extensions ... and adding an optional permission for the user to grant ... to enable/disable the detection mechanism. 

That might actually be a good idea.

**Comment by atomGit** [comment]
i didn't pay close enough attn. when reading the descriptions - i get it now :)

regarding fingerprinting/privacy, detect feeds injects a script - assuming JS is enabled for the site, does this open a potential fingerprint avenue? there's nothing in the manifest about 'web accessible resources' so i wasn't sure

**Comment by igorlogius** [comment]
All good, i actually have to thank you for providing the idea of merging the addons. 
Less code maintainace on my side. 

Regarding the content script injection. The injected script is wrapped inside an anonymous function, and should not be directly  detectable. Double so, since it doesn't make any changes, but only reads (aka. parses)  some values and passes them onto the toolbar/pageAction  popup.

I am not 100% sure what the  ... web accessible resources ...  are for, but if you had to guess, i would say ... to connect/request external  assest or websites.  That is something this addon simply doesn't need.  No external site is requested / used in any way. 
Everything happens locally. 

Hope that answers your questions.

**Comment by atomGit** [comment]
i believe (not 100% sure) web accessible resources are resources which an extension makes available to the page/server - i don't think it's about pulling remote resources

descrip. from 'pants' of the arkenfox user.js with regard to how they are listed in the manifest: "An array of strings specifying the paths of packaged resources that are expected to be usable in the context of a web page"

the reason i asked about it is because the use of them _can_, but not necessarily, leak the extension UUID which can aid in fingerprinting the browser - [here's an issue](https://github.com/arkenfox/user.js/issues/1018#issuecomment-699566996) i brought up if you're interested

**Comment by igorlogius** [comment]
You are right. From what i understand from the issue and the official mdn resource 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources
i would say, that list-feeds and none of my other addons expose their internal urls.   

Simple reason being,  that the content-script injection is only/mostly done via `tabs.executeScript` (ref. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript) 
or via the manifest.json, via content-script.  

I try to not use anything that isn't absolutely required, so no other resouces are injected, which might expose usable information for fingerprinting. 

At least so long as there is no implementation bug with mozillas Web-Extension implementation that i am not aware of.

**Comment by atomGit** [comment]
> I try to not use anything that isn't absolutely required ...

i like your ethic - i always check extensions the best i can before installing, especially since the WE API change which seemed to bring all the unethical malware/adware/tracking/fingerprinting devs from Google Chrome to Firefox

**Comment by igorlogius** [comment]
>  i always check extensions the best i can before installing ...
A very wise decision. 

> ... the WE API change ...  seemed to bring all the unethical malware/adware/tracking/fingerprinting devs from Google Chrome to Firefox
Yeah, the AMO review process isn't very strict, maybe in the future Mozilla will improve this, but i wouldn't hold my breath. 

Anyway, If you have any further questions about this or any other addon of mine  feel free to open an issue, and i'll try to answer to the best of my abilites.
