### ISSUE TITLE
generic feed detection

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#31]
https://perishablepress.com (by Jeff Starr) is a WordPress site, so i don't know what Jeff did here, but the feed is not detected - there is a link in the HTML however...

`<a target="_blank" href="/feed/" title="Articles served in RSS format">RSS</a>`

i'm not suggesting that a feed parser be written for this specific website, however i wonder if a generic parser for such a case may be useful elsewhere - given i don't know JS at all, i'm not able to write one, but i'm thinking along the lines of...

`(?i)href="(feed|rss|atom)"`

...and then just prepending the domain

**Comment by igorlogius** [comment]
i'll take a look and try to find out, why the feed isn't being detected.

**Comment by igorlogius** [comment]
Hi again. 

i recently added a new default rule, which tries to detect rss links which dont have any type identifiers (like the one on the wordpress site). But it only gets added on the inital addon installation, which is why you havent seen it yet. But you can simply add it. Here are the relevant parts.

### JS Code

```
const feeds = [];
document.querySelectorAll('a').forEach( (link) => {
if(typeof link.href === 'string'){
	for( word of ['rss','feed','atom'] ){
		if(link.innerText.toLowerCase().indexOf(word) > -1){
			feeds.push(link.href);
		}
	}
}
});
return feeds;
```

### 

URL RegEx: 

`^https:\/\/.*`


Both can also be found in the `custom-feed-detectors.json`


The result should look like this: 

![snip_20230217-203731](https://user-images.githubusercontent.com/67047467/219772395-2042bbdc-f1c0-408c-b663-d1a2aca64f59.png)


Thanks again for the feedback.

**Comment by atomGit** [comment]
ha! i looked in custom-feed-detectors.json before i opened this issue for such a rule but i apparently missed it - sorry about that :)
