### ISSUE TITLE
add a feed preview view

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#5]
if you're feeling a little ambitious :)

would be nice to be able to preview feeds, sand boxed and sanitized HTML - i'm guessing there's a library laying around somewhere, or see [this add-on](https://addons.mozilla.org/en-US/firefox/addon/feed-preview/)

**Comment by igorlogius** [comment]
Hi, unfortunetly i still havent found a good library for this.

The addon you linked, seems to have implemented the parsing in a "not-so" reusable way ... and jsonfeed support is also sadly non existent.

I feel like if it take on the "feed preview" feature, i can not do a half-ass job, 
since there are already a bunch of other feed reader addons.
That is why  i am a little hesitant / discuraged to even start. 

But i'll think about this again ... and reevaluate my positon. 
If i change my mind, i'll add an update here. 

In any case, thanks for the feedback.

**Comment by igorlogius** [comment]
I'll soonish ( in the next couple of weeks)  be taking another look at this ...  (if nothing keeps me from it) 
But it seems likely that i will have to use a low level library like sax.js  (ref. https://github.com/isaacs/sax-js)  for the xml stuff.  
I will most likel just use it to convert everything into some unified  JSON format and use that  to render/create the feed preview from.

**Comment by atomGit** [comment]
test-only is fine :)

**Comment by atomGit** [comment]
looks good - thanks for taking this on!

don't know how far you might take this, but a dark theme might be something to consider

**Comment by atomGit** [comment]
i tend to think that loading the feed preview would be better done in a new tab verses the pop-up, especially if decide to implement image/iframe loading

**Comment by igorlogius** [comment]
@atomGit  

Should be fixed  in 1.9.16
Sidenote: I already set `target="_blank"` to the links, but for some strange reason that did not help (maybe some about:config settings interfere, i am not sure),  so now i catch the click action and "manually" open the links in a new tab. Hope that helps.

**Comment by igorlogius** [comment]
@atomGit  If possible, open new issues and dont reuse old ones. Thanks.
