### ISSUE TITLE
[Bug Report]  bitchute feed detection does work with certain channels 

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#9]
ex: `https://www.bitchute.com/channel/bombardsbodylanguage/`

list-feed returns: 1 feed found `https://www.bitchute.com/channel/bombardsbodylanguage/`

it should return: `https://www.bitchute.com/feeds/rss/channel/bombardsbodylanguage`

list-feeds v1.8.10 (bitchute was broken in previous version also)

**Comment by igorlogius** [comment]
I'll check it.

**Comment by igorlogius** [comment]
There seems to be an issue with the spaces in the channel owner name. 
I updated the  `custom-feed-detectors.json`  which you can import  or  
you can also edit the rule yourself 

regex: `^https:\/\/www\.bitchute\.com\/channel\/.*`

code: 
```javascript
const feeds = [];
let feedUrl;
const url = new URL(window.location.href);
const parts = url.pathname.split('/');
if(parts.length > 1) {
  if (parts[1] === 'channel') {
    const channelname_selector = '.image-container > a:nth-child(1)';
    const channelname = document.querySelector(channelname_selector).href.split('/channel/')[1];
    if(channelname !== '') {
      feedUrl = new URL('/feeds/rss/channel/' + channelname ,url.origin);                                                               
      feeds.push(feedUrl.toString());
    }
  }
}
return feeds;
```

If you think that you can improve the bitchute feed detection feel free to open an issue with the suggestion
and i'll gladly add it to the `custom-feed-detectors.json`.

**Comment by atomGit** [comment]
since you mentioned a problem with spaces i'm guessing you're getting the channel name from the page title perhaps?

if that's the case, maybe you can grab it from the URL instead to avoid this problem

this would not work if the user is viewing a video, but it would if they're viewing the channel page and, far as i'm concerned, that's totally fine

**Comment by igorlogius** [comment]
The reason i did not use the URL (on the new and old detection) is simply because bitchute does not always seem use the channel name inside the url. 

Example: 

This link/channel  https://www.bitchute.com/channel/lauralynntylerthompson/
redirects to https://www.bitchute.com/channel/BodlXs2IF22h/

And sadly the feed only seems to be available via https://www.bitchute.com/feeds/rss/channel/lauralynntylerthompson/
and not https://www.bitchute.com/feeds/rss/channel/BodlXs2IF22h/ 

To also show the feed on the `video` site ... the script and regex would only be need to to modified slightly. 
I updated the `custom-feed-detectors.json`  to include the change but here again if you want to manually do it.

url_regex: `^https:\\/\\/www\\.bitchute\\.com\\/.*`

code: 
```javascript
const feeds = [];
let feedUrl;
const url = new URL(window.location.href);
const parts = url.pathname.split('/');
if(parts.length > 1) {
  if (parts[1] === 'channel' || parts[1] === 'video') {
    const channelname_selector = '.image-container > a:nth-child(1)';
    const channelname = document.querySelector(channelname_selector).href.split('/channel/')[1];
    if(channelname !== '') {
      feedUrl = new URL('/feeds/rss/channel/' + channelname ,url.origin);                                                               
      feeds.push(feedUrl.toString());
    }
  }
}
return feeds;
```

**Comment by atomGit** [comment]
> For Example, if i nomally click on a channel link on the main page https://www.bitchute.com/
> i get urls which don't contain the actual channel name and instead ...

does that happen on the actual channel page though?

**Comment by igorlogius** [comment]
> does that happen on the actual channel page though?
Havent seen it there yet, but ... i am not very familar with bitchute, i just noticed the "edge case" and thought that it could be something worth evading if possible, since i guess that you sometimes browse over the main page to maybe discover new channels or videos ... and i thought it would be annoying if the feed did not work correctly then. 

 But if you are sure you really only  want to rely on the URL, i guess you could use this code: 


```javascript 
const feeds = [];
let feedUrl;
const url = new URL(window.location.href);
const parts = url.pathname.split('/');
if(parts.length > 2) {
  if (parts[1] === 'channel' || parts[1] === 'video') {
    const channelname = parts[2];
    if(channelname !== '') {
      feedUrl = new URL('/feeds/rss/channel/' + channelname ,url.origin);                                                               
      feeds.push(feedUrl.toString());
    }
  }
}
return feeds;
```

But i personlly would NOT recommend it.
